org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.233
neo_version_range=[21.1.233,)
loader_version_range=[4,)

gateways_file_id=6926284
placebo_file_id=6926281
apothic_attributes_file_id=7445079
jei_version=19.27.0.340

mod_id=jei_gateways
mod_name=JEI Gateways
mod_license=All Rights Reserved
mod_version=1.1.2
mod_group_id=com.hp
mod_authors=
mod_description=
